Greek
openmultiplayer/homepage pull request #87
Opened 2019-04-25 15:55 UTC by treboryx

Added Greek in the list of languages, everything translated and updated the table.

2019-04-25 15:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmultiplayer/homepage?pullRequest=87) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/openmultiplayer/homepage?pullRequest=87) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: whitesource-bolt-for-github[bot]<br/>:x: treboryx<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmultiplayer/homepage?pullRequest=87) it.</sub>

2019-04-26 08:41 UTC, Southclaws requested changes

2019-04-26 08:41 UTC, Southclaws commented on .whitesource
> +##########################################################
Not relevant to this PR.

2019-04-26 08:45 UTC, Southclaws commented
Thanks for the contribution, however it seems you've used some kind of bot in this PR which has inserted some random config file.

Since you need to rebase anyway, I recommend you run `git rebase -i HEAD~2` and remove the commit ffa49248903e2bc0a46562635880f6101f70d099 completely from the tree - this will resolve the license/cla check as well as the rogue file.

Thanks!

2019-04-26 09:15 UTC, treboryx commented
My apologies. The bot is automatic and checks for vulnerable packages.

I have done as you requested.

2019-04-26 13:44 UTC, Southclaws approved these changes

2019-04-26 13:58 UTC, merged